import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav/Nav";
import Footer from "../components/footer/Footer";
import PropTypes from "prop-types"; // /fix 'children' is missing in props validation
// The problem is that the children prop is not validated using PropTypes. To fix this, you need to add PropTypes validation for the children prop.

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

export const metadata = {
  title: "Novatech Solutions",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
  return (
    <html lang="sv">
      <body className={`${robotoSlab.variable} antialiased`}>
        <Nav></Nav>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}