import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav/Nav";
import Footer from "../components/footer/Footer";

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} antialiased`}>
        <Nav></Nav>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
